"""
Django settings for club_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import dj_database_url
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i!4((ygkw5i!d-3*zih+eug*yo86b((^dmfc-w_sr7!nswogok'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

# club_project/settings.py
INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # REQUIRED for django-allauth
    'django.contrib.sites',
    
    # 3rd party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Enables Google Login
    
    # My apps
    'accounts', # Your custom app!
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Add this line specifically:
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'club_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'club_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# If we are on Render, use their database. If on laptop, use SQLite.
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# 1. TELL DJANGO WHERE TO LOOK FOR YOUR FILES (Local)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# 2. TELL DJANGO WHERE TO COLLECT THEM FOR PRODUCTION (The Fix!)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 3. ENABLE WHITENOISE (To serve files on Render)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# club_project/settings.py

# Tells Django to use our custom user model defined in accounts/models.py
AUTH_USER_MODEL = 'accounts.CustomUser'
# club_project/settings.py

# Unique ID required by allauth
SITE_ID = 1

# Tell allauth how to authenticate users (we want email/password)
AUTHENTICATION_BACKENDS = [
    # Required for Django Admin
    'django.contrib.auth.backends.ModelBackend',
    # Required for allauth (local & social)
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Redirects after successful login/logout (can be customized later)
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# General allauth settings
ACCOUNT_USERNAME_REQUIRED = False      # Users will not need a separate username
ACCOUNT_EMAIL_REQUIRED = True          # Email is mandatory
ACCOUNT_UNIQUE_EMAIL = True            # Every email must be unique
ACCOUNT_AUTHENTICATION_METHOD = 'email' # Log in using email, not username
# Tells allauth to use our custom form for signups
ACCOUNT_FORMS = {'signup': 'accounts.forms.CustomSignupForm'}
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Allow unsecured login for localhost development
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'